jiakuan/gwt-gradle-plugin

gwt-gradle-plugin/src/main/java/org/wisepersist/gradle/plugins/gwt/GwtEclipsePlugin.java
Regarding #6 I simply s/com.google/com.gwtplugins/ in this file and tested locally with snapshot and it does now enable the feature properly using eclipse 4.7 and the gwt plugin version 3.0.0.
This will now not work with gwt plugin versions less than 3.0.0.
=> Reflect eclipse plugin nature name change from to com.gwtplugins

gwt-gradle-plugin/src/main/java/org/wisepersist/gradle/plugins/gwt/GwtCompile.java, gwt-gradle-plugin/src/main/java/org/wisepersist/gradle/plugins/gwt/GwtDraftCompile.java
Support the gradle build cache for the compile tasks. Other tasks may be candidates for this as well. See also https://blog.gradle.org/introducing-gradle-build-cache.
=> Make compile tasks `@Cacheable`

gwt-gradle-plugin/src/main/java/org/wisepersist/gradle/plugins/gwt/internal/GwtVersion.java
jiakuan/gwt-gradle-plugin#17 broke version numbers like 2.8.0-rc1 or 2.8.0.1. This fix restores support for these version numbers.
=> Fix version number parsing in GwtVersion.

gwt-gradle-plugin/src/main/java/org/wisepersist/gradle/plugins/gwt/GwtBasePlugin.java
Adding dependencies to the `runtimeElements` configuration is deprecated in Gradle 6. It's only meant for querying the dependencies by consumers. Using the plugin with Gradle 6 shows:
> **The runtimeElements configuration has been deprecated for dependency declaration.**
> This will fail with an error in Gradle 7.0. Please use the implementation or compileOnly or runtimeOnly configuration instead.
I think the dependency should be added to the `runtimeOnly` configuration instead. but please correct me if I'm wrong.
=> Gradle 6+: use runtimeOnly configuration instead of runtimeElements for declaring dependencies

src/main/java/org/wisepersist/gradle/plugins/gwt/AbstractGwtTask.java, src/main/java/org/wisepersist/gradle/plugins/gwt/GwtBasePlugin.java, src/main/java/org/wisepersist/gradle/plugins/gwt/GwtSuperDev.java
This PR aims to fix #36.
* The `work` and `cache` directories have been marked as internal, so they don't end up in the task outputs.
* The `extra` and `gen` have been made optional and the defaults have been removed. This way, these directories and their contents are only created when explicitly configured.
=> Fix outputs of the compileGwt task

.gitignore, build.gradle, src/main/java/org/wisepersist/gradle/plugins/gwt/AbstractGwtActionTask.java, src/main/java/org/wisepersist/gradle/plugins/gwt/GwtBasePlugin.java, src/main/java/org/wisepersist/gradle/plugins/gwt/GwtCompile.java, src/main/java/org/wisepersist/gradle/plugins/gwt/internal/GwtVersion.java, src/test/java/org/wisepersist/gradle/plugins/gwt/internal/GwtVersionTest.java
but setting an illegal value for gwtVersion will cause an exception
(instead of warning)
GwtVersion.parseOrNull() removed.
New testcase.
=> #47 Not setting gwtVersion will not cause a warning

doc/use-cases/Working with Eclipse.md
The version in which eclipse support was removed is 1.12.0 not 1.2.0.
=> Fix confusing version info regarding eclipse

src/main/java/org/wisepersist/gradle/plugins/gwt/AbstractGwtActionTask.java, src/main/java/org/wisepersist/gradle/plugins/gwt/GwtBasePlugin.java, src/main/java/org/wisepersist/gradle/plugins/gwt/internal/GwtVersion.java, src/test/java/org/wisepersist/gradle/plugins/gwt/internal/GwtVersionTest.java
Fixes #60 
EDIT: checked with running code in SuperDev mode and with compiling to JS, both worked fine. Also all artifacts from `./gradlew :dependencies` show the correct group ID.
=> Use org.gwtproject as group ID for GWT >= 2.10

src/main/java/org/docstr/gradle/plugins/gwt/GwtBasePlugin.java
This is an improvement to my previous PR, it leaked dependencies needed only at compile time to the runtime classpath. Sorry for overlooking that
=> Issue #66: Do not leak compile dependencies

src/main/java/org/docstr/gradle/plugins/gwt/GwtSuperDev.java, src/main/java/org/docstr/gradle/plugins/gwt/GwtSuperDevOptions.java, src/main/java/org/docstr/gradle/plugins/gwt/internal/GwtSuperDevOptionsImpl.java
SuperDev Mode has [a `-style` parameter](https://www.gwtproject.org/articles/superdevmode.html), which currently cannot be used with this plugin. This PR adds this parameter.
=> Add -style parameter to SuperDev Mode

src/main/java/org/docstr/gradle/plugins/gwt/GwtSuperDev.java
I oversaw this line, which is actually required to make the change of #69 work.
=> Fix: Add -style parameter to convention Mapping

doc/setup-and-configuration/Configuration References.md, gradle.properties, src/main/java/org/docstr/gradle/plugins/gwt/AbstractGwtActionTask.java
In case you are specifying a [Java toolchain](https://docs.gradle.org/current/userguide/toolchains.html)
to compile your Java files with a higher version of Java than the one running Gradle, GWT compilation might fail.
This allows plugins users to avoid that -- I made it configurable since I'm not sure if that's a good idea by default (e.g. the someone may want to run Gradle and GWT in Java 11 and default Java compilation in Java 8 ...)
=> Allow using Java version from toolchain

src/main/java/org/docstr/gradle/plugins/gwt/GwtCompilerPlugin.java
Added back the missing task class reference to fix #72 .
=> Fix: checkGwt task does not delegate to GwtCheck class #72

doc/setup-and-configuration/Configuration References.md
Mistake from #71 -- the option is only intrduced for task, not the extension object.
=> Fix toolchain option docs

doc/setup/Configuration References.md, src/main/java/org/docstr/gradle/plugins/gwt/AbstractGwtCompile.java, src/main/java/org/docstr/gradle/plugins/gwt/GwtCompile.java, src/main/java/org/docstr/gradle/plugins/gwt/GwtCompileOptions.java, src/main/java/org/docstr/gradle/plugins/gwt/internal/GwtCompileOptionsImpl.java
Adds the "-setProperty" parameter to the gwt compiler options. This partially addresses #4
=> add -setProperty gwt compiler option

src/main/java/org/docstr/gradle/plugins/gwt/internal/GwtVersion.java, src/test/java/org/docstr/gradle/plugins/gwt/internal/GwtVersionTest.java
This makes it possible to use the plugin with the HEAD snapshot of GWT (https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/gwt/ )
=> Accept HEAD-SNAPSHOT as version number

plugin/src/main/java/org/docstr/gwt/GwtTestConfig.java, plugin/src/main/java/org/docstr/gwt/options/GwtTestOptions.java
- Fix: When running GwtTest, if a GWTTestCase is defined, the code in GWTTestCase also needs to be transpiled from Java to JavaScript. During this process, specifying the JDK version used to write the code is crucial to ensure proper transpilation. When executing tests through JUnit, parameters are passed using the gwt.args property. However, it seems the sourceLevel parameter, which indicates the Java version, is missing (though other parameters have not been verified). The latest GWT supports syntax introduced in JDK 11 and later. Without this option, modern constructs like var or enhanced switch expressions cannot be used in GWTTestCase code.
- Fix: SourceSet can be added in the user's build script. For example, when using 'dagger-gwt', the annotation processor generates Java files, …
=> Fix gwt test

plugin/src/main/java/org/docstr/gwt/GwtCompileConfig.java
Hi,
we've been using the v1 version of this plugin for about a 6 months I guess (thanks!), and we are considering moving to v2.
We have multiple GWT modules in one Gradle source set, and only one of them has an `entry-point` element.  So guessing the source path from that doesn't work for us.  We could add the `<source path="client"/>` to all the modules, but that seems unnecessary, because:
As mentioned in
https://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html if no `source` or `public` element is defined in a module XML file, the `client` and `public` subpackage is implicitly added to the source/public path as if `<source path="client" />` or `<public path="public">` had been found in the XML.
So, that is what this PR is about.  What do you think?
=> Support for default source and public paths

plugin/src/main/java/org/docstr/gwt/GwtCompileConfig.java
In my previous PR I broke the tests.  Sorry about that.  I though they were broken in main branch, but they were only broken on Windows.
Here's what I learned.
```java
import java.io.File;
import java.util.TreeSet;
final String path = "/foo";
final TreeSet<File> t = new TreeSet<>();
// The order of add calls doesn't matter here.
// Just mimicking the order of extractSourcePaths.
t.add(new File(path, "MyModule.gwt.xml"));
t.add(new File(path, "client"));
System.out.println(t);
// On Windows: [\foo\client, \foo\MyModule.gwt.xml]
// On Linux:   [/foo/MyModule.gwt.xml, /foo/client]
```
For me, the "Linux" here was just `docker run -it azul/zulu-openjdk:17-latest jshell`. I'm now using zulu 17 on Windows, too, since that seems to be on your CI.
So, on Windows, "c" comes before "M", but some of …
=> In tests, use TreeSet that orders the same on all OSes

plugin/src/main/java/org/docstr/gwt/GwtPlugin.java, plugin/src/main/java/org/docstr/gwt/GwtPluginExtension.java, plugin/src/main/java/org/docstr/gwt/options/GwtTestOptions.java
Hi,
the plugin configures all tasks of type Test, and it seems to interfere with how Gradle sets up the testing frameworks.
I've created a small but representative [demo app](https://github.com/vmj/gradle-jvm-test-suites-with-gwt) that is using [JVM Test Suites](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html).  Which is what we use in my current project.
If you checkout the demo app code and try to follow the README, you will notice that some of the test suites fail to initialize any of the tests.
To make them work:
1. In your checkout of the `gwt-gradle-plugin`, switch to this PR branch
2. In the demo app, edit the `settings.gradle` to include the plugin build
3. In the demo app, edit the `build.gradle` to disable the test task configuration
Let me know what you …
=> Allow user to configure which test tasks to configure

plugin/src/main/java/org/docstr/gwt/AbstractBaseTask.java, plugin/src/main/java/org/docstr/gwt/GwtTestConfig.java
instead of overwriting it, so that users can configure additions to the tasks' classpath.
Closes #88
=> Add to classpath in AbstractBaseTask

README.md, gradle/libs.versions.toml, plugin/src/test/java/org/docstr/gwt/GwtPluginFunctionalTest.java
I included 8.1 (lowest supported) and 8.9 - 8.12 (latest four).  The versions between work, too, but are disabled just to save time/bandwith/space.
I removed the comment about Java versions.  If someone is using an old Gradle version, then it is probably obvious they can't use certain Java versions, regardless of this plugin.
=> Test the plugin agains different Gradle versions

plugin/src/main/java/org/docstr/gwt/GwtCompileTask.java
Enable build caching for GWT compilation tasks by adding the `@CacheableTask` annotation. This allows Gradle to cache and reuse compilation outputs when inputs haven't changed, significantly improving build performance.
- Adds `@CacheableTask` annotation to `GwtCompileTask`
- No changes to task behavior - only enables caching capability
- All required inputs and outputs were already properly annotated
- **Performance improvement**: GWT compilation can be skipped when inputs haven't changed (saves up to 6 minutes per build as reported in #106)
- **Better developer experience**: Faster incremental builds when working on backend-only changes
- **CI optimization**: Cached outputs can be shared across builds and machines with remote cache
=> Enable build caching for GwtCompileTask
